version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shopping
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 30s
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql-container
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"

  producer:
    build:
      context: ./producer
    container_name: producer-service
    depends_on:
      - rabbitmq
      - mysql
    ports:
      - "5000:5000"
    volumes:
      - ./producer:/app
    command: python /app/producer.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5

  consumer:
    build:
      context: ./consumer
    container_name: consumer-service
    depends_on:
      - rabbitmq
      - mysql
    volumes:
      - ./consumer:/app
    command: python /app/consumer.py

volumes:
  mysql_data:
